---

- name: nome playbook
  hosts: all
  tasks:
   - name: testando se um arquivo existe
     command: "test -f /etc/profile.d/dexter"
     register: result
     ignore_erros: yes

   - name: configurando uma variavel do sistema
     shell: echo "export DEXTER=/opt/dexter > /etc/profiled/dexter"
     when: result.rc == 0
